#!/bin/bash

help()
{
    echo -e "A script for Arch Linux distro that get a list of mirrors based on a given ISO country code from Pacman Mirrorlist Generator and rank them by speed
    	Usage as root: fastml [options...]
    	Options:
    		-h, -H, --help	Show help text
    		-c, -C, --country	Define a country by its ISO 2-code" 
    
    exit 0
}

if [ $# -eq 0 ]; then
    help
fi

while [ "$1" != "" ]; do
    case $1 in
        -c | -C | --country )    shift
                            country="$1"
                            ;;
        -h | -H | --help )       help
                            ;;
    esac
    shift
done

if [ "$EUID" -ne 0 ];then
    echo -e "Execute it as root"
    exit 1
fi

files=$(ls /etc/pacman.d/ -1 | grep -c -E "mirrorlist(\.backup\.\d+)?")
mirrorlist_url="https://archlinux.org/mirrorlist/?country=$country&protocol=http&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on"

if ! text=$(curl -s "$mirrorlist_url"); then
	echo "Something went wrong"
	exit 1
fi

cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup."$files"

sed -e "s/^#Server/Server/" -e "/^#/d" <<< "$text" | rankmirrors - > /etc/pacman.d/mirrorlist

pacman -Syy

exit 0
