#!/bin/bash
# FIXME: Broken. spotifyd is highly suspected to be the culprit

art_path="$HOME/.cache/spotifyd/arts"
mkdir -p "$art_path"

if [[ "$PLAYER_EVENT" == "play" ]] || [[ "$PLAYER_EVENT" == "change" ]]; then
	status="Now playing"

elif [[ "$PLAYER_EVENT" == "pause" ]]; then
	status="Paused"

else
	exit 1
fi

metadata=$(playerctl metadata -f "{{ mpris:artUrl }}\{{ title }}\{{ artist }}" -p "spotifyd")

art_url="$(cut -d '\' -f1 <<< "$metadata")"
song="$(cut -d '\' -f2 <<< "$metadata")"
artist="$(cut -d '\' -f3 <<< "$metadata")"
art_id="$(grep -o -E "\w+$" <<< "$art_url")"

art_path="$art_path/$art_id"

if [ ! -f "$art_path" ]; then
	curl -s -o "$art_path" "$art_url" > /dev/null
fi

notify-send "$status" "$song by $artist" -i "$art_path" -a "Spotify Player"

exit 0
